# Generated by Django 4.0.2 on 2022-07-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_profile_last_name'),
        ('posts', '0011_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to='users.Profile'),
        ),
    ]
