# Generated by Django 4.0.2 on 2022-07-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_profile_last_name'),
        ('posts', '0012_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to='users.Profile'),
        ),
    ]
