# Generated by Django 4.0.2 on 2022-07-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_profile_last_name'),
        ('posts', '0013_alter_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to='users.Profile'),
        ),
    ]
