# Generated by Django 4.0.2 on 2022-07-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_message_is_read'),
        ('posts', '0016_bookmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmarks',
            new_name='Bookmark',
        ),
    ]
