# Generated by Django 4.0.2 on 2022-07-18 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_message_is_read'),
        ('posts', '0017_rename_bookmarks_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
