# Generated by Django 4.0.2 on 2022-07-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_remove_bookmark_post_bookmark_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='post',
            field=models.ManyToManyField(blank=True, to='posts.Post'),
        ),
    ]
