# Generated by Django 4.0.2 on 2022-07-04 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_message_is_read_remove_message_recipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='sender',
            new_name='chat_member_one',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='recipient',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_member_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_member_two', to='users.profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
